chunker:
  class_name: 'semantic'
  model_name: 'BAAI/bge-reranker-v2-m3'
  max_chunk_size: 1000

triplet:
  class_name: 'original'
  validate: False
  entity_list_type: 'default' # Can be default of nerel
  batch_size: 128

generator:
  class_name: 'original_generator'
  batch_size: 128

reranker:
  class_name: 'cross_encoder_reranker'
  model_name: 'BAAI/bge-reranker-v2-m3'
  top_k: 20

graph:
  batch_size: 128
  which_level: 0



