chunker:
  class_name: 'semantic'
  model_name: 'BAAI/bge-reranker-v2-m3'
  max_chunk_size: 2000

triplet:
  class_name: 'original'
  validate: False
  entity_list_type: 'nerel' # Can be default of nerel
  batch_size: 128

generator:
  class_name: 'original_generator'
  batch_size: 1

reranker:
  class_name: 'hybrid_reranker_top_k'
  bm25_weight: 0.25
  semantic_weight: 0.75
  top_k: 5

graph:
  batch_size: 128
  which_level: 0
  enable_index: True
  embedder_model_name: 'all-MiniLM-L6-v2'



